# Runs test test suite
name: Node.js CI
on:
  pull_request:
    branches: ['main', 'dev']
  push:
    branches: 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:10.18-jessie # Run in NodeJS container
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        uses: actions/setup-node@v2
        with:
          node-version:
          cache: 'npm'
      - run: npm ci
      - run: npm run test:ci
